-- CreateTable
CREATE TABLE "Insurance" (
    "id" SERIAL NOT NULL,
    "buyerName" TEXT NOT NULL,
    "mobileNumber" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "buyerType" TEXT NOT NULL,
    "insuranceCategory" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "followUp" TEXT NOT NULL,
    "assignTo" TEXT NOT NULL,
    "comment" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "pin" TEXT NOT NULL,
    "gender" TEXT NOT NULL,
    "maritalStatus" TEXT NOT NULL,
    "dob" TEXT NOT NULL,
    "occupation" TEXT NOT NULL,
    "annualIncome" TEXT NOT NULL,
    "pan" TEXT NOT NULL,
    "adhar" TEXT NOT NULL,
    "gst" TEXT NOT NULL,
    "nomineeName" TEXT NOT NULL,
    "nomineeAge" TEXT NOT NULL,
    "nomineeRelation" TEXT NOT NULL,
    "referenceName" TEXT NOT NULL,
    "referenceNumber" TEXT NOT NULL,
    "registerNumber" TEXT NOT NULL,
    "make" TEXT NOT NULL,
    "model" TEXT NOT NULL,
    "variant" TEXT NOT NULL,
    "engineNumber" TEXT NOT NULL,
    "chassiNumber" TEXT NOT NULL,
    "makeMonthYear" TEXT NOT NULL,
    "registerMonthYear" TEXT NOT NULL,
    "insuranceCompany" TEXT NOT NULL,
    "branch" TEXT NOT NULL,
    "policyType" TEXT NOT NULL,
    "policyNumber" TEXT NOT NULL,
    "issueDate" TEXT NOT NULL,
    "dueDate" TEXT NOT NULL,
    "ncbDiscount" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Insurance_pkey" PRIMARY KEY ("id")
);
